version: '3.1'

services:

  db:
    container_name: postgres
    image: cr.yandex/crp5kg6f7gau4u16u5it/psql14:latest
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: atlas
      POSTGRES_DB: db01


  web:
    container_name: website
    image: cr.yandex/crp5kg6f7gau4u16u5it/atlas:latest
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: atlas
      POSTGRES_DB: db01
    links:
      - db
