version: '3.1'

services:

  db:
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: atlas
      POSTGRES_DB: db01
    ports:
      - "5432:5432"

  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: atlas
      POSTGRES_DB: db01
    links:
      - db
