# Generated by Django 4.0.4 on 2022-05-18 13:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_alter_atlasuser_objects_ai_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlasuser',
            name='objects_ai_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None, verbose_name='Группы доступа Ai'),
        ),
        migrations.AlterField(
            model_name='atlasuser',
            name='objects_cmn_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None, verbose_name='Группы доступа Сmn'),
        ),
    ]
