version: '3.6'

services:

  db:
    container_name: postgres
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: atlas
      POSTGRES_DB: db01


  web:
    container_name: website
    build: ./app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: atlas
      POSTGRES_DB: db01
    links:
      - db


  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    container_name: rabbitmq
    hostname: atlas
    ports:
        - "5672:5672"
        - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: atlasrabbit
    volumes:
      - ./rabbit/data/:/var/lib/rabbitmq/
      - ./rabbit/log/:/var/log/rabbitmq
    links:
      - web

