# Generated by Django 4.0.4 on 2022-06-16 11:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='error',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='error_end_date',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='error_start_date',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='info',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='sts',
        ),
        migrations.AlterField(
            model_name='sensorevent',
            name='date_of_service_planned',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 16, 14, 3, 12, 667183), verbose_name='Запланировано'),
        ),
        migrations.CreateModel(
            name='SensorError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.IntegerField(blank=True)),
                ('error_start_date', models.DateTimeField(blank=True, verbose_name='Дата начала ошибки')),
                ('error_end_date', models.DateTimeField(blank=True, verbose_name='Дата окончания ошибки')),
                ('sts', models.IntegerField(blank=True)),
                ('info', models.CharField(max_length=100, verbose_name='Описание')),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='error_sensor', to='atlas.object', verbose_name='Датчик')),
            ],
        ),
    ]
