# Generated by Django 4.0.4 on 2022-06-21 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='id_error_log',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_error', to='atlas.sensorerror', verbose_name='Журнал ошибки'),
        ),
    ]
