# Generated by Django 4.0.4 on 2022-06-16 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_remove_sensordata_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='info',
            field=models.CharField(blank=True, max_length=100, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='object',
            name='info',
            field=models.CharField(blank=True, max_length=100, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='info',
            field=models.CharField(blank=True, max_length=100, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='sensorerror',
            name='info',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sensorevent',
            name='date_of_service_planned',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 16, 14, 7, 27, 900019), verbose_name='Запланировано'),
        ),
        migrations.AlterField(
            model_name='useraccessgroups',
            name='info',
            field=models.CharField(blank=True, max_length=100, verbose_name='Информация'),
        ),
    ]
