# Generated by Django 4.0.4 on 2022-06-16 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0003_alter_company_info_alter_object_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ['name'], 'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['name'], 'verbose_name': 'Датчик', 'verbose_name_plural': 'Датчики'},
        ),
        migrations.AlterModelOptions(
            name='sensordata',
            options={'verbose_name': 'Данные', 'verbose_name_plural': 'Показатели датчиков'},
        ),
        migrations.AlterModelOptions(
            name='sensorerror',
            options={'verbose_name': 'Ошибка', 'verbose_name_plural': 'Ошибки'},
        ),
        migrations.AlterModelOptions(
            name='sensorevent',
            options={'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterModelOptions(
            name='useraccessgroups',
            options={'verbose_name': 'Группа доступа', 'verbose_name_plural': 'Группы доступа'},
        ),
        migrations.RemoveField(
            model_name='sensormlsettings',
            name='name',
        ),
        migrations.AddField(
            model_name='sensormlsettings',
            name='info',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sensorevent',
            name='date_of_service_planned',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 16, 14, 17, 16, 980885), verbose_name='Запланировано'),
        ),
    ]
