# Generated by Django 4.0.4 on 2022-06-16 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0004_alter_company_options_alter_object_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensormlsettings',
            options={'verbose_name': 'Настройка ML', 'verbose_name_plural': 'Настройки ML'},
        ),
        migrations.AlterField(
            model_name='sensorevent',
            name='date_of_service_planned',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 16, 14, 19, 33, 200742), verbose_name='Запланировано'),
        ),
    ]
