# Generated by Django 4.0.5 on 2022-06-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0004_alter_sensordata_id_error_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='id_sensor_repr',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Номер датчика в объекте'),
        ),
    ]
