# Generated by Django 4.0.4 on 2022-06-16 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0005_alter_sensormlsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sensorerror',
            name='error',
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sensorerror',
            name='sts',
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sensorevent',
            name='date_of_service_planned',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 16, 14, 41, 33, 167836), verbose_name='Запланировано'),
        ),
    ]
