# Generated by Django 4.0.5 on 2022-06-22 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0005_sensor_id_sensor_repr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='id_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_sensor', to='atlas.sensor', verbose_name='Датчик'),
        ),
        migrations.AlterField(
            model_name='sensorerror',
            name='id_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='error_sensor', to='atlas.sensor', verbose_name='Датчик'),
        ),
        migrations.AlterField(
            model_name='sensormlsettings',
            name='id_sensor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_sensor', to='atlas.sensor', verbose_name='Датчик'),
        ),
    ]
