# Generated by Django 4.0.5 on 2022-06-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0006_alter_sensordata_id_sensor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorerror',
            name='error_end_date',
            field=models.DateTimeField(null=True, verbose_name='Дата окончания ошибки'),
        ),
        migrations.AlterField(
            model_name='sensorerror',
            name='info',
            field=models.CharField(max_length=100, null=True, verbose_name='Описание'),
        ),
    ]
