# Generated by Django 4.0.4 on 2022-06-16 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0006_alter_company_name_alter_sensorerror_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorevent',
            name='date_of_service_planned',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 16, 15, 27, 29, 438656), verbose_name='Запланировано'),
        ),
    ]
