# Generated by Django 4.0.4 on 2022-06-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0006_alter_atlasuser_division_alter_atlasuser_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlasuser',
            name='division',
            field=models.CharField(blank=True, default=str, max_length=50, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='atlasuser',
            name='middle_name',
            field=models.CharField(blank=True, default=str, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='atlasuser',
            name='organization',
            field=models.CharField(blank=True, default=str, max_length=50, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='atlasuser',
            name='post',
            field=models.CharField(blank=True, default=str, max_length=50, verbose_name='Должность'),
        ),
    ]
