# Generated by Django 4.0.4 on 2022-06-16 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0007_alter_sensorevent_date_of_service_planned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorevent',
            name='date_of_service_planned',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 16, 15, 34, 24, 791223), verbose_name='Запланировано'),
        ),
    ]
