# Generated by Django 4.0.4 on 2022-06-16 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0008_alter_sensorevent_date_of_service_planned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorevent',
            name='date_of_service_planned',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Запланировано'),
        ),
    ]
