# Generated by Django 4.0.4 on 2022-06-14 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0008_object_objectevent_ai_object_cmn_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Cхема'),
        ),
        migrations.AlterField(
            model_name='objectevent',
            name='date_of_service_planned',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 14, 16, 3, 46, 727821), verbose_name='Запланировано'),
        ),
    ]
