# Generated by Django 4.0.4 on 2022-06-14 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0009_object_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectevent',
            name='date_of_service_planned',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 14, 17, 7, 38, 123973), verbose_name='Запланировано'),
        ),
    ]
