# Generated by Django 4.0.5 on 2022-06-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0009_alter_sensormlsettings_id_sensor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlasuser',
            name='division',
            field=models.CharField(default=str, max_length=50, null=True, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='atlasuser',
            name='middle_name',
            field=models.CharField(default=str, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='atlasuser',
            name='organization',
            field=models.CharField(default=str, max_length=50, null=True, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='atlasuser',
            name='post',
            field=models.CharField(default=str, max_length=50, null=True, verbose_name='Должность'),
        ),
    ]
