# Generated by Django 4.0.4 on 2022-06-14 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0010_alter_objectevent_date_of_service_planned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectevent',
            name='date_of_service_planned',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 14, 17, 8, 34, 549454), verbose_name='Запланировано'),
        ),
    ]
