# Generated by Django 4.0.5 on 2022-06-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0012_alter_atlasuser_division_alter_atlasuser_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensormlsettings',
            name='setting_type',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Тип'),
        ),
    ]
