# Generated by Django 4.0.5 on 2022-06-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0013_alter_sensormlsettings_setting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectevent',
            name='date_of_service_completed',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Выполненно'),
        ),
    ]
