# Generated by Django 4.0.5 on 2022-06-29 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0014_alter_objectevent_date_of_service_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectevent',
            name='id_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_object', to='atlas.object', verbose_name='Датчик'),
        ),
        migrations.AlterField(
            model_name='objectevent',
            name='plan',
            field=models.CharField(max_length=300, verbose_name='План работ'),
        ),
    ]
