# Generated by Django 4.0.5 on 2022-07-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0016_atlasuser_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectevent',
            name='operating_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Наработка, час'),
        ),
    ]
