# Generated by Django 4.0.5 on 2022-07-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0017_objectevent_operating_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectevent',
            name='operating_time',
        ),
    ]
