# Generated by Django 4.0.5 on 2022-07-12 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0021_alter_company_name_alter_object_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorerror',
            name='id_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='error_event', to='atlas.objectevent', verbose_name='Ошибка'),
        ),
        migrations.AlterField(
            model_name='sensorerror',
            name='id_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_sensor', to='atlas.sensor', verbose_name='Датчик'),
        ),
    ]
