# Generated by Django 4.0.5 on 2022-07-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0023_sensordata_setting_h_sensordata_setting_hh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorerror',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержденная'),
        ),
    ]
