# Generated by Django 4.0.5 on 2022-07-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0024_sensorerror_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='id_sensor_repr',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Номер объекта для rabbit'),
        ),
    ]
