# Generated by Django 4.0.5 on 2022-07-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0025_object_id_sensor_repr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='id_sensor_repr',
            new_name='id_object_repr',
        ),
    ]
