# Generated by Django 4.0.5 on 2022-07-26 10:34

import atlas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0026_rename_id_sensor_repr_object_id_object_repr'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorerror',
            name='date_of_confirmation',
            field=models.DateTimeField(null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AlterField(
            model_name='object',
            name='image',
            field=models.ImageField(blank=True, upload_to=atlas.models.get_image_name, verbose_name='Мнемосхема'),
        ),
    ]
