# Generated by Django 4.0.5 on 2022-08-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0027_sensorerror_date_of_confirmation_alter_object_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='mnemonic_scheme_pos',
            field=models.IntegerField(blank=True, default=-1, verbose_name='Положение на мнемосхеме'),
        ),
    ]
